# Generated by Django 5.0.4 on 2024-04-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorRecord',
            fields=[
                ('id', models.CharField(default='1', max_length=50, primary_key=True, serialize=False)),
                ('sensor', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
