# Generated by Django 5.0.4 on 2024-04-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeless', '0002_fan_schedule_light'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='light',
            name='schedule',
        ),
        migrations.AddField(
            model_name='light',
            name='schedules',
            field=models.ManyToManyField(related_name='lights', to='homeless.schedule'),
        ),
    ]
