# Generated by Django 5.0.4 on 2024-04-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeless', '0003_remove_light_schedule_light_schedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fan', 'Fan'), ('light', 'Light')], max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('is_auto', models.BooleanField(default=False)),
            ],
        ),
    ]
