# Generated by Django 5.0.4 on 2024-04-21 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeless', '0005_remove_activitylog_action_activitylog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fan',
            old_name='activate_temp',
            new_name='threshold',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='deactivate_temp',
        ),
    ]
