# Generated by Django 5.0.4 on 2024-04-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeless', '0007_remove_activitylog_is_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='id',
            field=models.CharField(default='1', max_length=50, primary_key=True, serialize=False),
        ),
    ]
