# Generated by Django 5.0.6 on 2024-05-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeless', '0010_activitylog_is_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanLog',
            fields=[
                ('id', models.CharField(default='1', max_length=50, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('is_manual', models.BooleanField(default=False)),
                ('threshold', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LightLog',
            fields=[
                ('id', models.CharField(default='1', max_length=50, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
