# Generated by Django 5.0.6 on 2024-05-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeless', '0011_fanlog_lightlog_delete_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanAutoLog',
            fields=[
                ('id', models.CharField(default='1', max_length=50, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_manual', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FanThresholdLog',
            fields=[
                ('id', models.CharField(default='1', max_length=50, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('threshold', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fanlog',
            name='is_manual',
        ),
        migrations.RemoveField(
            model_name='fanlog',
            name='threshold',
        ),
    ]
