# Generated by Django 5.0.6 on 2024-05-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeless', '0012_fanautolog_fanthresholdlog_remove_fanlog_is_manual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='everyday',
        ),
    ]
